---

- include_tasks: "{{ ansible_facts.os_family | lower }}.yml"

- import_tasks: 'route_table_configuration.yml'
  tags: configuration

- import_tasks: 'bond_configuration.yml'
  when: interfaces_bond_interfaces is defined
  tags: configuration

- import_tasks: 'bridge_configuration.yml'
  when: interfaces_bridge_interfaces is defined
  tags: configuration

- import_tasks: 'ethernet_configuration.yml'
  when: interfaces_ether_interfaces is defined
  tags: configuration

- name: Debian | Merge configuration in interface file
  assemble:
    src: "{{ interfaces_net_path['debian'] }}"
    dest: /etc/network/interfaces
  tags: configuration
  when:
    - ansible_facts.os_family | lower == 'debian'
    - interfaces_merge

- import_tasks: 'service.yml'
  tags: service
