---
- name: RedHat | install current/latest network packages versions
  become: true
  package:
    name: '{{  interfaces_pkgs["redhat"][ansible_distribution_major_version] }}'
    state: '{{ interfaces_pkg_state }}'
  tags: package
